inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
    - "**/*_test.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_test.rb"
