inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - 'test/**/*'
    - 'lib/neo/sdk/simulation/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 24

Metrics/MethodLength:
  Max: 24
