inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'test/**/*'
    - 'lib/neo/sdk/simulation/*'
Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 24
Metrics/MethodLength:
  Max: 24
